#ifndef DEV_RUNNER_H
#define DEV_RUNNER_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* DEV_RUNNER_H */
